apiVersion: v1
kind: Secret
metadata:
  name: murza-secret
type: Opaque
data:
  MYSQL_PASSWORD: U29iYWthc29iYWthMQ==
  MAIL_SENDER_ACCESS_USERNAME: a29zdHlhNjc4OTAxMjczQGdtYWlsLmNvbQ==
  MAIL_SENDER_ACCESS_PASSWORD: b3BreiBwd3ZmIGZ5cXkgYmdtdg==
  AWS_ACCESS_KEY_ID: QUtJQVFXSENQV1pIMkVQWEFMNkU=
  AWS_SECRET_ACCESS_KEY: cDY4UG40N3BPVHdWdHk3anBlOUF2cWRuYld6WllqZUFrWDM=
  TWILIO_SMS_SENDER_PHONE: KzEzMTM3Nzc4MTM2
  TWILIO_SMS_SENDER_SID: QUMwZTdhOWNlNmY2ZWMzZjM5YTQwZjZjMjU3NDc2OWZhZg==
  TWILIO_SMS_SENDER_TOKEN: YThlM2RlMDg0YjFkMmJlN2IyZGE4NjBjNjE0MDc5M2Q=
  RECAPTCHA_SECRET: NkxkaFM0Y3FBQUFBQUlEUUFDb1ZOUlE4UElhQTJZTDlqWFRFV3Q0NQ==
  JWT_SECRET: ZjA3NjM0ZDBlMWVmNmI2ZWI4OWU3OTJlYmFmNWE1N2U0YmEzOTQzOGIwYTFiNDhiZTkxZTQ2NGI2NGM5ZjI0OQ==
  SUPER_ADMIN_PASSWORD: MTIzNDU2Nzg=
  SUPER_ADMIN_EMAIL: c3VwZXIuYWRtaW5AZ21haWwuY29t
  MYSQL_ROOT_PASSWORD: cm9vdDE=

